# Generated by Django 3.2.5 on 2021-07-14 14:18

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='About Me', max_length=255, unique=True)),
                ('subtitle', models.CharField(default='This section is about me!', max_length=255)),
                ('image', models.ImageField(default='default.jpg', upload_to='About/')),
                ('description', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Home',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Apurv Chatur', max_length=20, unique=True)),
                ('subtitle', models.CharField(default='Django Web Developer', max_length=50)),
                ('image', models.ImageField(default='default.jpg', upload_to='Home/')),
                ('description', ckeditor.fields.RichTextField()),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Intrest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Python', max_length=255, unique=True)),
                ('subtitle', models.CharField(default='I love it!', max_length=255)),
                ('image', models.ImageField(default='default.jpg', upload_to='Intrest/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Qrazzers', max_length=255, unique=True)),
                ('subtitle', models.CharField(default='Coding website!', max_length=255)),
                ('image', models.ImageField(default='default.jpg', upload_to='Project/')),
                ('description', ckeditor.fields.RichTextField()),
                ('category', models.CharField(blank=True, choices=[('PP', 'Personal Project'), ('CP', 'Client Project')], max_length=2, null=True)),
                ('visit_url', models.URLField(default='https://github.com/ApurvChatur/', max_length=255)),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
