# Generated by Django 3.2.5 on 2021-09-21 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectDesign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='intrest',
            name='image',
        ),
        migrations.AddField(
            model_name='project',
            name='code_url',
            field=models.URLField(default='https://github.com/ApurvChatur/', max_length=255),
        ),
    ]
