# Generated by Django 3.2.5 on 2023-05-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectDesign', '0002_auto_20210921_1333'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='resume',
            field=models.ImageField(default='default.pdf', upload_to='About/'),
        ),
    ]
