# Generated by Django 3.2.5 on 2023-05-04 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectDesign', '0005_intrest_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Certificate', max_length=255, unique=True)),
                ('subtitle', models.CharField(default='I love it!', max_length=255)),
                ('image', models.ImageField(default='default.jpg', upload_to='Certificate/')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
        ),
    ]
