# Generated by Django 3.2.5 on 2023-05-04 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectDesign', '0006_certificate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='certificate',
            name='image',
        ),
        migrations.AddField(
            model_name='certificate',
            name='file',
            field=models.FileField(default='default.jpg', upload_to='Certificate/'),
        ),
    ]
