# Generated by Django 3.2.5 on 2023-05-23 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectDesign', '0010_alter_home_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='home',
            name='subtitle',
            field=models.CharField(default='Python Developer', max_length=50),
        ),
    ]
